Use unreleased sled
Problem: When trying to add this repo into full-cli-rs, we get the
following error:

```
error: failed to select a version for `crossbeam-channel`.
    ... required by package `pagecache v0.19.4`
    ... which is depended on by `sled v0.28.0`
    ... which is depended on by `libconsensus-dag v0.0.2
(https://github.com/Fantom-foundation/libconsensus-dag#5f76933e)`
    ... which is depended on by `full-cli-rs v0.0.2
(/home/agustin/work/fantom/full-cli-rs)`
versions that meet the requirements `^0.3.9` are: 0.3.9

all possible versions conflict with previously selected packages.

  previously selected package `crossbeam-channel v0.3.8`
    ... which is depended on by `tokio-executor v0.2.0-alpha.6
(https://github.com/Fantom-foundation/tokio#1cae04f8)`
    ... which is depended on by `tokio v0.2.0-alpha.6
(https://github.com/Fantom-foundation/tokio#1cae04f8)`
    ... which is depended on by `full-cli-rs v0.0.2
(/home/agustin/work/fantom/full-cli-rs)`

failed to select a version for `crossbeam-channel` which could resolve
this conflict
```

The only way to solve is to patch either tokio or sled to use a
different crossbeam-channel version. sled is easier to patch. However,
the repo version of sled is not sync with the version in crate and has
breaking, relevant changes: They removed the package `pagecache` and
merged into sled. So we have to use the unreleased version. Next commit
will change the git url for _our_ unreleased version.